---
title: "Lyden av 2025!"

format:
  html:
    code-fold: true
---

<!-- 
Til meg selv: 
Kjør `quarto preview index.qmd` i datafortelling-mappen. 
Husk å aktivere venv! 
-->

```{python}
import polars as pl
import plotly.express as px
from data_setup import combine_data_sources

year = 2025
df_ = combine_data_sources()
df = df_.filter(pl.col("track_played_utc").dt.year() == year)
```

```{python}
( 
  df_
  .group_by(pl.col("track_played_utc").dt.year().alias("year"))
  .agg(total_scrobbles = pl.len())
  .filter(pl.col("year").is_in([x for x in range(2021, 2025+1)]))
  .sort(pl.col("year"), descending=False)
  .with_columns(pct_change=pl.col("total_scrobbles").pct_change())
  .sort(pl.col("year"), descending=True)

)
```

Ulikt Spotify teller Last.fm i "scrobbles" som tilsier at du har hørt på en låt, og skiller seg
derfor fra Spotify sine antall minutter som de viser i sin "Wrapped." 

I 2025 har lyttingen en nedgang i antall scrobbles på 18% fra året før og er det laveste
tallet de siste 5 årene. Ved min egen oppfatning er ikke denne nedgangen noe overraskende da
jeg har forsøkt å kutte ut musikk som bakgrunnstøy når jeg gjør noe f.eks. jobbe med noe, surfe
på nettet eller er ute og går.

## Lyttetrend utover 2025
```{python}
from scipy.signal import savgol_filter

df_trend = (
    df
    .group_by(pl.col("track_played_utc").dt.date())
    .agg(n_scrobbles=pl.len())
    .sort(pl.col("track_played_utc"), descending=False)
    .with_columns(weekday = pl.col("track_played_utc").dt.strftime("%A"))
)

signal = df_trend.select("n_scrobbles").to_numpy().flatten()
filtered_signal = savgol_filter(signal, window_length=15, polyorder=3)
df_trend = df_trend.with_columns(trend_scrobbles=filtered_signal)

px.line(
    df_trend, x="track_played_utc", y=["n_scrobbles", "trend_scrobbles"],
    )
```

Ved å bruke et Savitzky-Golay filter kan vi tydeliggjøre trenden over hvordan lyttemønsteret
mitt har utviklet seg utover året. Vi ser at store deler av lyttingen er blitt unnagjort i den
første halvdelen av året. Naturlig kommer dette av at jeg jobbet med masteroppgaven min i
disse månedene, hvor vi ser en stor nedgang i aktivitet utover junimåned (sett gjennom 
`trend_scrobbles`).

Det som er interessant å bemerke seg er det repeterende mønsteret i andre halvdel av året hvor
man har en topp etterfulgt av en mindre topp som så daler ned i bunn fra august av.


```{python}
( 
  df_trend
  .select("track_played_utc", "n_scrobbles")
  .sort("n_scrobbles", descending=True)
  .head(5)
)
```

På sett og vis er det gøy å kunne knytte opp dagene med stor aktivitet i lytting til konkrete
hendelser, og igjen naturlig nok er dette knyttet opp mot masteren:

 * `2025-06-12` på toppen er dagen før muntlig forsvar,

 * `2025-05-13` og `2025-05-14` er de to foreløpende dagene til innlevering av oppgaven.


## Sammenhengende lytting

```{python}
def listening_streak(df:pl.DataFrame, year:int=2025):
    df = df.filter(
        pl.col("track_played_utc").dt.year() == year
    )

    dates = df.select(
        pl.col("track_played_utc").dt.date().unique().alias("date")
    )

    listening_streak = dates.with_columns(
        is_break = pl.col("date").diff() != pl.duration(days=1) 
    ).with_columns( 
        streak_id = pl.col("is_break").fill_null(True).cum_sum()
    )

    streak_stats = (
        listening_streak
        .group_by(pl.col("streak_id"))
        .agg(
            start_date = pl.col("date").min(),
            end_date = pl.col("date").max(),
            streak_length = pl.len()
        )
    )
    streak_stats = streak_stats.sort(pl.col("streak_length"), descending=True)

    return streak_stats

listening_streak(df, year=year)
```

Dette er for meg overraskende men samtidig ikke. At jeg har klart å opprettholde en "streak"
på 212 dager er imponerende, men at det kun har vært 2 dager av det foregående året hvor
jeg ikke åpnet opp Spotify-appen er urovekkende.

For å sette dette i perspektiv kan vi se på heatmappet under^[Her får jeg ikke helt til å ordne
opp i de store sidemarginene av plottet.]

```{python}
import plotly.graph_objects as go
import polars as pl

df_heatmap = (
    df
    .group_by(pl.col("track_played_utc").dt.date())
    .agg(
      tracks_scrobbled=pl.len()
    )
    .sort(pl.col("track_played_utc"), descending=False)
    .with_columns(
        week=pl.col("track_played_utc").dt.strftime("%W").cast(int),
        weekday=pl.col("track_played_utc").dt.weekday(),
        date_str=pl.col("track_played_utc").dt.strftime("%Y-%m-%d"),
    )
)

min_week = df_heatmap["week"].min()
max_week = df_heatmap["week"].max()

all_weeks = list(range(min_week, max_week + 1))

fig_heatmap = go.Figure(
    data=go.Heatmap(
        z=df_heatmap["tracks_scrobbled"],
        x=df_heatmap["week"],
        y=df_heatmap["weekday"],
        colorscale="Emrld",
        showscale=True,
        xgap=3,
        ygap=3,
        hovertext=df_heatmap["date_str"],
        hovertemplate="<b>Date:</b> %{hovertext}<br><b># Scrobbles:</b> %{z}<extra></extra>",
    )
)

fig_heatmap.update_layout(
    title=f"{year} lytteaktivitet",
    height=200,
    width=800,
    xaxis=dict(
        showgrid=False,
        zeroline=False,
        tickmode="array",
        tickvals=all_weeks[::3],
        ticktext=[f"{w+1}" for w in all_weeks[::3]],
        tickfont=dict(size=10),
    ),
    yaxis=dict(
        showgrid=False,
        zeroline=False,
        autorange="reversed",
        tickvals=[x for x in range(1, 8)],
        ticktext=["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        tickmode="array",
        scaleanchor="x",
        side="left"
    ),
    plot_bgcolor="rgba(0,0,0,0)",
    margin=dict(t=40, b=40, l=40, r=40),
)
fig_heatmap.show()
```

_Vurdere å ha ett heatmap for H1 og ett for H2 for å få fram bedre nyanser_

## Når foregår lyttingen?

```{python}

# hourly histogram
df_peak_hours = (
  df
  .group_by(
    pl.col("track_played_utc")
    .dt.convert_time_zone(time_zone="Europe/Berlin")
    .dt.hour().alias("hour")
  )
  .agg(scrobbles_by_hour = pl.len()) 
  .sort("scrobbles_by_hour", descending=True)
)

fig_hour_hist = px.histogram(
  df_peak_hours, x="hour", y="scrobbles_by_hour", nbins=24, text_auto=".0f",
)
fig_hour_hist.update_layout(
  bargap=0.2,
  xaxis=dict(title="time"),
  yaxis=dict(title="antall scrobbles")
  )
fig_hour_hist.update_traces(textfont_size=10, textangle=0, textposition="outside", cliponaxis=False)
```

```{python}
# daily histogram
weekdays = {1: "Mandag", 2: "Tirsdag", 3: "Onsdag", 4: "Torsdag",
            5: "Fredag", 6: "Lørdag", 7: "Søndag"}

df_daily_hist = (df
    .group_by(pl.col("track_played_utc").dt.weekday().alias("weekday_idx"))
    .agg(scrobbles_by_weekday = pl.len())
    .sort("scrobbles_by_weekday", descending=True)
    .with_columns(weekday = pl.col("weekday_idx").replace_strict(weekdays, default=None).alias("weekday"))
)

fig_daily_hist = px.histogram(
  df_daily_hist, x="weekday", y="scrobbles_by_weekday", nbins=7, text_auto=".0f",
  category_orders={"weekday": list(weekdays.values())}
)
fig_daily_hist.update_layout(
  bargap=0.2, 
  xaxis=dict(title="ukedag"), 
  yaxis=dict(title="antall scrobbles")
)
fig_daily_hist.update_traces(textfont_size=10, textangle=0, textposition="outside", cliponaxis=False)
```

Ut ifra den fordelingen av døgnets timer er det klart at mesteparten av lyttingen foregår i
nitiden fram firetiden, etterfulgt av en periode fra fire til syv på ettermiddagen; vi har en
bimodal fordeling hvor det er størst aktivitet på formiddagen etterfulgt av en mindre aktiv
periode på ettermiddagstid.

Av hverdagene (man-fre) er det tirsdag som ikke helt er på samme nivå som resten. Lørdag og
søndag derimot ser vi en sterk nedgang i musikklytting.


<!-- ## Test -->
<!---->
<!-- ```{python} -->
<!-- from plotly.subplots import make_subplots -->
<!-- import plotly.graph_objects as go -->
<!---->
<!-- # Create subplots (1 row, 2 columns) -->
<!-- fig = make_subplots( -->
<!--     rows=1, cols=2, -->
<!--     subplot_titles=("Scrobbles time for time", "Scrobbles fordelt på ukedagene") -->
<!-- ) -->
<!---->
<!-- fig.add_trace( -->
<!--     go.Bar( -->
<!--         x=df_peak_hours["hour"], -->
<!--         y=df_peak_hours["scrobbles_by_hour"], -->
<!--         text=df_peak_hours["scrobbles_by_hour"], -->
<!--         textposition="outside", -->
<!--         textfont=dict(size=10), -->
<!--         hovertemplate="%{x}:00 - %{y} scrobbles<extra></extra>", -->
<!--         marker=dict(color="steelblue"), -->
<!--         name="By Hour" -->
<!--     ), -->
<!--     row=1, col=1 -->
<!-- ) -->
<!---->
<!-- fig.add_trace( -->
<!--     go.Bar( -->
<!--         x=df_daily_hist["weekday"], -->
<!--         y=df_daily_hist["scrobbles_by_weekday"], -->
<!--         text=df_daily_hist["scrobbles_by_weekday"], -->
<!--         textposition="outside", -->
<!--         textfont=dict(size=10), -->
<!--         hovertemplate="%{x} - %{y} scrobbles<extra></extra>", -->
<!--         marker=dict(color="coral"), -->
<!--         name="By Weekday" -->
<!--     ), -->
<!--     row=1, col=2 -->
<!-- ) -->
<!---->
<!-- fig.update_layout( -->
<!--     height=500, -->
<!--     width=1200, -->
<!--     showlegend=False, -->
<!--     bargap=0.2 -->
<!-- ) -->
<!---->
<!-- fig.update_xaxes(title_text="Time av dagen", row=1, col=1) -->
<!-- fig.update_xaxes(title_text="Ukedag", row=1, col=2,  -->
<!--                  categoryorder="array",  -->
<!--                  categoryarray=list(weekdays.values())) -->
<!---->
<!-- fig.update_yaxes(title_text="Scrobbles", row=1, col=1) -->
<!-- fig.update_yaxes(title_text="Scrobbles", row=1, col=2) -->
<!---->
<!-- fig.show() -->
<!-- ``` -->



## Artister og låter som utgjorde året
```{python}
import plotly.express as px

# number of scrobbles per artists and scrobbles per track
df_artists = (
    df
    .group_by(pl.col("artist_name"), pl.col("track_name"))
    .agg(
      track_scrobbles = pl.len(), # scrobbles per track
    )
    .with_columns(
      artist_scrobbles=pl.col("track_scrobbles").sum().over("artist_name") # total artist scrobbles
    )
    .sort(pl.col("artist_scrobbles"), descending=True)
)

# Get top 25 artists w.r.t. artist scrobbles
top_n = 25
top_n_artists = df_artists.select("artist_name").unique(maintain_order=True).head(top_n)
df_top_n_artists = ( 
    df_artists
    .join(top_n_artists, on="artist_name", how="semi") 
    .sort("track_scrobbles", descending=True)
)

fig_artists = px.bar(
  df_top_n_artists, 
  y="artist_name", 
  x="track_scrobbles", 
  color="track_scrobbles",
  hover_data=["artist_scrobbles", "track_name", "track_scrobbles"],
  title=f"Mest lyttede artister + låtfordeling {year}"
)
fig_artists.update_yaxes(
    categoryorder="total descending",
    autorange="reversed"
)
fig_artists.update_traces(textfont_size=10, textangle=0, textposition="outside", cliponaxis=False)
fig_artists.update_yaxes(autorange="reversed", dtick=1)
fig_artists.show()
```
I de nedre sjiktene av min topp 25 ser man at artistene gjerne har én sang som utmerker seg som
favoritt. Lengre opp i rangeringen derimot er det en håndfull av sanger som har blitt spilt en
god del.

```{python}
top_artists = (
    df
    .group_by("artist_name")
    .agg(total_scrobbles = pl.len())
    .sort("total_scrobbles", descending=True)
)

# How large portion does my top n artists make out my total listening
(
    top_artists
    .select(
        pl.col("total_scrobbles").limit(top_n).sum().alias(f"top_{top_n}_total_scrobbles"),
        pl.col("total_scrobbles").sum().alias("total_scrobbles")
    )
    .with_columns(
        (pl.col(f"top_{top_n}_total_scrobbles") / pl.col("total_scrobbles"))
        .alias("artist_loyalty_score")
    )
)
```

Og de 25 artistene utgjør litt over en fjerdedel av den totale lyttingen min.


```{python}
top_n_tracks = ( 
    df_artists
    .select(pl.col("artist_name"), pl.col("track_name"), pl.col("track_scrobbles"))
    .sort(pl.col("track_scrobbles"), descending=True)
    .with_columns(
      full_track_name = pl.col("artist_name") + pl.lit(" | ") + pl.col("track_name")
    )
    .head(top_n)
)

fig_tracks = px.bar(
  top_n_tracks, 
  y="full_track_name", 
  x="track_scrobbles", 
  hover_data=["artist_name", "track_name", "track_scrobbles"],
  title=f"Mest lyttede låter {year}",
  text_auto=".0f"
)
fig_tracks.update_yaxes(
    categoryorder="total descending",
    autorange="reversed"
    )
fig_tracks.update_traces(textfont_size=10, textangle=0, textposition="outside", cliponaxis=False)
fig_tracks.update_yaxes(autorange="reversed", dtick=1)
fig_tracks.show()

top_n_tracks.group_by("artist_name").agg(songs_in_top_n = pl.len()).sort("songs_in_top_n",
descending=True).head()
```
I plottet ovenfor her har vi en tydeligere oversikt over hvilke låter som har blitt spilt av
mest. Dean Blunt sin "5" skiller seg ut min mest spilte låt, hvor mellomrommene i avspillinger
blir smalere.

Selv om Bladee utvilsomt var min mest lyttede artist, etterfulgt av Dean Blunt, utgjør de to
artistene kun 4 sanger av topp 25 her – en mangfoldig top 25 ellers.


