name: etl-recent-listening-history-test
run-name: ${{ github.actor }} retrieving newest listening data from Last.fm
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *" # daily at midnight

jobs:
  etl-script:
    name: python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # enables committing and pushes to the repository

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.11.8"

      - name: Install project
        run: uv sync --locked

      - name: Extraction, transform and loading
        env:
          CLIENT_ID: ${{ secrets.LAST_FM_CLIENT_ID }}
        run: |
          uv run "data retrieval/get_recent_history.py"

      - name: Check for changes
        id: git-check
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add .
          git diff --cached --quiet || echo "changes=true" >> $GITHUB_ENV

      - name: Commit and push if changes
        if: ${{ env.changes == 'true' }}
        run: |
          git commit -m "test data from retrieval script"
          git push
